config/routes.rb
Rails.application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'home#index'
  resources :boats, path: 'boats-for-sale', only: [:index, :show]
  resources :bookings, only: [:create]

  get :contact, to: 'home#contact', as: :contact
end

app/models/boat.rb
class Boat < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  validates_presence_of :name, :description, :safety, :fishing, :comfort, :storage
  validates_length_of :name, :short_description, maximum: 255

  def image
  	"#{name.downcase.gsub(/\s+/, '-')}.jpg"
  end

  has_one :boat_image
  has_one :boat_specifiction
  has_one :boat_price
end

app/models/boat_image.rb
class BoatImage < ActiveRecord::Base
end

app/models/boat_price.rb
class BoatPrice < ActiveRecord::Base
end

app/models/boat_specifiction.rb
class BoatSpecifiction < ActiveRecord::Base
end

app/models/booking.rb
class Booking < ActiveRecord::Base

  validates_presence_of :name, :email, :message
  validates_length_of :name, :phone, maximum: 50
end

app/models/currency.rb
class Currency < ActiveRecord::Base

  def self.default
    find_by(name: 'GBP')
  end

  def self.convert(amount, source, target)
    source ||= Currency.default
    return amount if source == target
    amount * target.rate / source.rate
  end
end

app/models/redactor_rails/asset.rb
class RedactorRails::Asset < ActiveRecord::Base
  include RedactorRails::Orm::ActiveRecord::AssetBase
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  validates_presence_of :data
end

app/models/redactor_rails/document.rb
class RedactorRails::Document < RedactorRails::Asset
  mount_uploader :data, RedactorRailsDocumentUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end

  def as_json_methods
    [:image]
  end
end

app/models/redactor_rails/picture.rb
class RedactorRails::Picture < RedactorRails::Asset
  mount_uploader :data, RedactorRailsPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  extend FriendlyId
  friendly_id :email, use: [:slugged, :finders]

  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :load_boats


  private

  def load_boats
  	@boats = Boat.all
  	@featured_boats = Boat.all
  end
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController

  def index
    session[:sort] = params[:sort] if params[:sort].present?
    session[:order] = params[:order] if params[:order].present?

    @response = Rails.cache.fetch "arvor.boats", expires_in: 1.day do
      JSON.parse(RestClient.get('http://eby.rightboatexpert.com/api/boats?keyword=arvor'))
    end

    @boats = @response['results']
    @boats = case session[:sort]
               when 'price', 'relevancy', 'smart'; @boats.sort_by { |x| x['price'] }
               when 'arrival'; @boats.sort_by { |x| x['stock_number'].downcase }
               when 'year'; @boats.sort_by { |x| (x['year'] || (Date.today.year - 20)) }
               else; @boats.sort_by { |x| x[session[:sort]] }
             end
    @boats = @boats.reverse if session[:order] && session[:order] == 'desc'
    @boats_all = Boat.all()
  end

  def show
    @boats = Boat.all()
    @boat  = Boat.find(params[:id])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      redirect_to :back, notice: 'Your request sent successfully.'
    else
      redirect_to :back, alert: 'Oops, something went wrong. Please try again later.'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:name, :phone, :email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_class_for(condition)
    if condition.is_a?(Regexp)
      return 'active' if "#{controller_path}##{action_name}" =~ condition
    else
      controller, action = condition.to_s.split('#')
      return 'active' if (controller_path.blank? || controller == controller_path) && (action.blank? || action == action_name)
    end
  end

  def bootstrap_class_for(flash_type)
    case flash_type.to_sym
      when :alert
        "warning"
      when :notice
        "info"
      else
        flash_type.to_s
    end
  end

  def price_in_euro(price, source_currency)
    target_currency = Currency.find_by(name: 'EUR')
    cp = Currency.convert(price, source_currency, target_currency)
    number_to_currency cp, precision: 0, unit: target_currency.symbol
  end
end

app/views/boats/_boat.html.haml
- if true#cache "boat_#{boat['id']}", expires: 1.hour do
  - slug = "#{boat['manufacturer'].downcase}-#{boat['model'].downcase}-#{boat['id']}"
  - url = "http://www.boats.co.uk/boats-for-sale/#{slug}"
  - image_url = "http://eby.rightboatexpert.com/api/images/#{boat['boat_image_id']}/450x450"
  - price = boat['price']
  - currency_name = boat['currency']
  - source_currency = Currency.find_by(name: currency_name)

  .boat.clearfix
    .marketing-status(class="marketing-status-#{boat['marketing_status'].downcase.gsub(/\s+/, '')}")
    .boat-detail.clearfix
      .boat-image
        = link_to image_url, 'data-lightbox' => slug do
          = image_tag image_url, alt: ''
      .boat-description
        %h2 #{boat['year']} #{boat['manufacturer']} #{boat['model']}
        %h2.price
          = number_to_currency price, precision: 0, unit: source_currency.try(:symbol) || Currency.default.symbol
          %small VAT #{boat['vat']}
          %small Approx. #{price_in_euro(price, source_currency)}
        %p
          Located:
          = image_tag "http://www.boats.co.uk/img/countries/#{boat['country_code'].downcase}.png", alt: boat['country_code']
          #{boat['location']}, #{boat['country']}
        %p Stock number: #{boat['stock_number']}
        %p= boat['description'].html_safe
        .boat-specs.clearfix
          - if boat['new_used'] == 'new'
            .boat-flags.boat-flag-new.popover-link{data: { toggle: 'popover', content: 'This means that this boat has never been sold to a registered keeper before. Typically this means that you will be the first owner and that you will receive all the benefits of a new boat namely : first owner, everything shiny and sparkly! , At least 1 year warranty on everything and 24 hour aftercare for your first year of ownership. The best bit about buying a new boat though is that you will have the latest technology and design and style in the marina ! Wow !', delay: '1000', html: 'true', 'original-title' => 'New Boat', trigger: 'hover', title: '', placement: 'top'} }
          - else
            .boat-flags.boat-flag-brokerage.popover-link{data: { toggle: 'popover', content: 'This means that Boats Ltd trading as Boats.co.uk (and our sister companies Princess East Coast, Princess Poole, Princess Cala dOr) are acting as agents in this sale for a third party owner. Typically brokerage boats will not include any warranty and will not allow part exchanges. We also recommend that all brokerage boats are surveyed and sea trailed (unless our sales staff advise otherwise). However we are careful about the boats we sell, so you can be reassured that if we have a boat for sale that we make our best efforts to ensure that the boat is worthy of our name.', delay: '1000', html: 'true', 'original-title' => 'Brokerage', trigger: 'hover', title: '', placement: 'top'} }
          .boat-flags{class: "#{boat['boat_share'] > 0 ? 'boat-flag-equity popover-link' : 'boat-flag-equityoff' }", data: {toggle: 'popover', content: 'This boat can be sold in shares. Normally this would be upto a maximum of 4 owners (For the 1/4 share price - divide by 4!). The boat will have a fixed location. Please get in touch if you wish to know more.', delay: '1000', html: 'true' , trigger: 'hover', title: 'Boat Share', placement: 'top'} }
          .boat-flags{class: "#{boat['part_exchange'] > 0 ? 'boat-flag-px popover-link' : 'boat-flag-pxoff'}", data: {toggle: 'popover', content: 'Put simply we will consider a part exchange of a boat, car or motorbike against this vessel. We are proud of our part exchanging and we are renowned for it ! So give us a try- you may be surprised!', delay: '1000', html: 'true' , trigger: 'hover', title: 'PX welcome', placement: 'top'} }
          .boat-flags{class: "#{boat['warranty'] > 0 ? 'boat-flag-warranty popover-link' : 'boat-flag-warrantyoff'}", data: {toggle: 'popover', content: 'This means that this boat will have a warranty included. Used boats typically include a 3 month warranty on major engine and drivetrain  Gearbox failure. Please check our T&Cs for a full breakdown on what is covered.', delay: '1000', html: 'true' , trigger: 'hover', title: 'Warranty', placement: 'top'} }
        %p
        = link_to '', url, class: 'moreinfo'

app/views/boats/index.html.haml
.container
  .page-header.box
    .content
      .pad.clearfix
        %h1
          Search results
          %small
            = @boats.count
            arvor boats for sale
        .sorts.pull-right
          .btn-group(role='group')
            %a.btn.btn-default.dropdown-toggle(type='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false')
              Sort by #{session[:sort]}
              %span.caret
            %ul.dropdown-menu
              %li= link_to 'price', boats_path(sort: 'price', order: session[:order])
              %li= link_to 'relevancy', boats_path(sort: 'relevancy', order: session[:order])
              %li= link_to 'manufacturer', boats_path(sort: 'manufacturer', order: session[:order])
              %li= link_to 'year', boats_path(sort: 'year', order: session[:order])
              %li= link_to 'arrival', boats_path(sort: 'arrival', order: session[:order])
              %li= link_to 'smart', boats_path(sort: 'smart', order: session[:order])
          .btn-group(role='group')
            %a.btn.btn-default.dropdown-toggle(type='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false')
              Order #{session[:order] == 'desc' ? 'high to low' : 'low to high'}
              %span.caret
            %ul.dropdown-menu
              %li= link_to 'low to high', boats_path(sort: session[:sort], order: 'asc')
              %li= link_to 'high to low', boats_path(sort: session[:sort], order: 'desc')

  .box
    .boats.content
      - if @boats.any?
        - @boats.each do |boat|
          = render 'boat', boat: boat
      - else
        %p No boats yet.

#links.se-slope{:style => "margin-bottom: -30px;"}
  .se-content
    .container
      .row
        .col-xs-6.col-md-3
          %ul.list-unstyled
            - @boats_all.each do |boat|
              %li
                = link_to boat_path(id: boat.slug) do
                  = boat.name
        .col-xs-6.col-md-3
          %ul.list-unstyled
            %li
              = link_to "/boats-for-sale" do
                Approved Used
            %li
              = link_to "/contact" do
                Contact

app/views/boats/show.html.haml
.container
  .boat-detail
    %h3.page-title #{@boat.name} - #{@boat.short_description}
    .pad
      %section
        #gallery
          - for i in 1..@boat.boat_image.count
            %img{"data-src" => asset_path("#{ @boat.boat_image.folder_name}/#{ i }.jpg")}
      %section
        %h4.sub-title
        = @boat.description.html_safe
      %section
        %h4.sub-title Safety
        = @boat.safety.html_safe
      %section
        %h4.sub-title Fishing
        = @boat.fishing.html_safe
      %section
        %h4.sub-title Comfort
        = @boat.comfort.html_safe
      %section
        %h4.sub-title Storage
        = @boat.storage.html_safe
      %section
        %h4.sub-title SPECIFICATIONS
        .container
          %table.table.table-striped.table-bordered
            %tbody
              %tr
                %td(style="width:300px;") Engine
                %td
                  = @boat.boat_specifiction.engine.html_safe
              %tr
                %td Length overall (including platform)
                %td
                  = @boat.boat_specifiction.length_overall.html_safe
              %tr
                %td Length of Hull
                %td
                  = @boat.boat_specifiction.length_of_hull.html_safe
              %tr
                %td Beam
                %td
                  = @boat.boat_specifiction.beam.html_safe
              %tr
                %td Height - Without Canvas
                %td
                  = @boat.boat_specifiction.height_without_canvas.html_safe
            %tbody
              %tr
                %td Draft
                %td
                  = @boat.boat_specifiction.draft.html_safe
              %tr
                %td Dry Weight
                %td
                  = @boat.boat_specifiction.dry_weight.html_safe
              %tr
                %td Fuel Capacity
                %td
                  = @boat.boat_specifiction.fuel_capacity.html_safe
              %tr
                %td CE Design Category
                %td
                  = @boat.boat_specifiction.ce_design_category.html_safe
              %tr
                %td Maximum Capacity
                %td
                  = @boat.boat_specifiction.maximum_capacity.html_safe
            %tbody
              %tr
                %td Maximum Load (People, Gear)
                %td
                  = @boat.boat_specifiction.maximum_load.html_safe
              %tr
                %td Maximum Power
                %td
                  = @boat.boat_specifiction.maximum_power.html_safe
              %tr
                %td Water Tank
                %td
                  = @boat.boat_specifiction.water_tank.html_safe
              %tr
                %td Fuel tank max capacity
                %td
                  = @boat.boat_specifiction.fuel_tank_max_capacity.html_safe
              %tr
                %td Fuel Tank Type
                %td
                  = @boat.boat_specifiction.fuel_tank_type.html_safe
      %section
        .container
          %table.table.table-striped.table-bordered
            %tbody
              %tr
                %td(style="width:300px;") Hull & Deck
                %td
                  = @boat.boat_specifiction.hull_deck.html_safe
              %tr
                %td Cockpit
                %td
                  = @boat.boat_specifiction.cockpit.html_safe
              %tr
                %td Bow
                %td
                  = @boat.boat_specifiction.bow.html_safe
              %tr
                %td Helm
                %td
                  = @boat.boat_specifiction.helm.html_safe
              %tr
                %td Cabin
                %td
                  = @boat.boat_specifiction.cabin.html_safe
              %tr
                %td Galley
                %td
                  = @boat.boat_specifiction.galley.html_safe
              %tr
                %td Head Equipment
                %td
                  = @boat.boat_specifiction.head_equipment.html_safe
      %section
        %h4.sub-title PRICING
        .container
          %table.table.table-striped.table-bordered
            %tbody
              %tr
                %td(style="width:300px;"){:rowspan => 2}
                  = image_tag @boat.image, class: 'img-responsive',style: "display: block; margin-left: auto; margin-right: auto;"
                %td
                  = @boat.boat_price.item.html_safe
              %tr
                %td(style="background-color:#1dadea; color: white; padding-left:40px; font-size:1.7em; font-weight: bold;")
                  = @boat.boat_price.price.html_safe

#links.se-slope{:style => "margin-bottom: -30px;"}
  .se-content
    .container
      .row
        .col-xs-6.col-md-3
          %ul.list-unstyled
            - @boats.each do |boat|
              %li
                = link_to boat_path(id: boat.slug) do
                  = boat.name
        .col-xs-6.col-md-3
          %ul.list-unstyled
            %li
              = link_to "/boats-for-sale" do
                Approved Used
            %li
              = link_to "/contact" do
                Contact
:javascript

  $(function() {
      var p = $("#gallery").portfolio({
        height: '300px', // gallery height
        width: '100%', // gallery width in pixels or in percentage
        logger: true

      });

      p.init();

  }); // end of ready();

app/views/bookings/_form.html.haml
= simple_form_for Booking.new, html: { class: 'form-horizontal', 'data-parsley-validate' => true }, wrapper: :horizontal_form do |f|
  .row
    .row-same-height.row-full-height
      .col-sm-10.col-xs-12.col-xs-height.col-full-height
        .row
          .col-md-9.col-md-offset-3.col-xs-12
            %h5 Please fill in the below fields, and we will be in touch.
        = f.input :name, input_html: { 'data-parsley-maxlength' => 50 }
        = f.input :phone, input_html: { label: 'Tel', 'data-parsley-maxlength' => 50 }
        = f.input :email, input_html: { 'data-parsley-maxlength' => 50 }
        = f.input :message, input_html: { rows: 8 }

      .col-sm-2.col-xs-12.col-xs-height.col-full-height
        = f.submit 'Send', class: 'btn btn-flat'

app/views/home/contact.html.haml
.se-container
  #main-bg.se-slope
    .se-content
      = image_tag 'boat.jpg', alt: '', class: 'img-responsive'
  .dummy.se-slope
  #contact.se-slope
    .se-content
      .container
        .contact-container
          %h3.page-title Contact Us
          .pad
            .clearfix
              .col-md-8.col-xs-12
                .row
                  .col-xs-12
                    %p
                      Welcome to Arvor UK.
                      %br
                      If you want to get answers and information about any of our products and services, get in touch with a Arvor Expert.
                    %p We also welcome feedback, so if we've helped you resolve a problem or you aren't happy with the service you've received, let us know so we can put things right.
                    %br
                .row
                  .col-xs-6
                    %p
                      Arvor UK
                      %br
                      Boats.co.uk
                      %br
                      Essex Marina
                      %br
                      Wallsea Island
                      %br
                      Essex SS4 2HF
                  .col-xd-6
                    %p
                      T: 01702 258 885
                      %br
                      E: #{mail_to 'info@arvorboats.co.uk', 'info@arvorboats.co.uk'}
                %br
            .row
              .col-xs-12
                = image_tag 'marina.jpg', class: 'img-responsive'

  = render 'shared/links'

app/views/layouts/application.html.haml
!!!
%html(lang='en')
  %head
    %meta(content='text/html; charset=UTF-8' http-equiv='Content-Type')
    %meta(charset='utf-8')
    %meta(content='IE=edge' http-equiv='X-UA-Compatible')
    %meta(content='width=device-width, initial-scale=1' name='viewport')
    %meta(content='' name='description')
    %meta(content='' name='author')
    %title Arvor
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    - if Rails.env.production?
      = javascript_include_tag 'https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js'
      = javascript_include_tag 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js'
    = stylesheet_link_tag 'application', media: 'all'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

  %body(class="#{controller_name}-#{action_name}")
    = render 'shared/header'

    #main-content
      = render 'shared/message'
      = yield

    #footer.se-slope
      .se-content
        .container.clearfix
          .copyright.pull-left
            &copy;#{Date.today.year} Arvor UK
          .footer-logo.pull-right
            = image_tag 'logo-boats.gif', alt: 'Boats.co.uk', width: 150

app/views/shared/_header.html.haml
%nav#header.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        = image_tag 'logo.png', alt: 'Arvor'
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        %li(class="#{nav_class_for('home#index')}")
          = link_to 'Home', root_path
        %li
          = link_to 'Arvor Range', '#', class: 'toggle-content', 'data-target' => '#featured-boats'
        %li(class="#{nav_class_for('boats#index')}")
          = link_to 'Approved Used', boats_path
        /%li
        /  = link_to 'Videos', 'javascript:void(0);'
        %li(class="#{nav_class_for('home#contact')}")
          = link_to 'Contact', contact_path

    %ul#featured-boats.list-unstyled
      - @featured_boats.each do |boat|
        %li
          = link_to boat_path(id: boat.slug) do
            = image_tag boat.image, alt: boat.name, class: 'img-responsive'
            %h4.boat-name= boat.name

app/views/shared/_links.html.haml
#links.se-slope
  .se-content
    .container
      .row
        .col-xs-6.col-md-3
          %ul.list-unstyled
            - @boats.each do |boat|
              %li
                = link_to boat_path(id: boat.slug) do
                  = boat.name
        .col-xs-6.col-md-3
          %ul.list-unstyled
            %li
              = link_to "/boats-for-sale" do
                Approved Used
            %li
              = link_to "/contact" do
                Contact

app/views/shared/_message.html.haml
- unless flash.blank?
  .flash-container
    .container
      - flash.each do |type, message|
        %div{class: "alert alert-#{bootstrap_class_for(type)} fade in"}
          %button.close{"data-dismiss" => "alert"} ×
          = message